### ISSUE TITLE
react-weui运行地址问题

### ISSUE THREAD

**Issue by Joodysen** [weui/react-weui#10]
按照开发文档运行react-weui工程成功之后打开http://localhost:8080这个网址会自动在URL后添加字段如   http://localhost:8080/#/?_k=v98vto ，点击每一个item后添加字段会改变，copy此URL到其他浏览器无法访问网址，请问是什么问题？

**Comment by progrape** [comment]
hash`#/?_k=v98vto`，是[react-router](https://github.com/rackt/react-router)加的。copy此URL到其他浏览器，是同一台机器的URL？同一台机器应该是可以访问的

**Comment by Joodysen** [comment]
@progrape 同一台机器的浏览器可以，有办法可以解决在其他机器以及安卓虚拟机上无法访问的问题吗，谢谢

**Comment by progrape** [comment]
网络互通就可以访问了，在同一个局域网的其他机器，可以通过你机器的IP来访问，Android虚拟机的也可以通过你宿主机的IP来访问的~

**Comment by Joodysen** [comment]
有点奇怪的是我的电脑访问http://localhost:8080/#/?_k=dtm8aa是可以的，把localhost改成主机ip号就不能访问了

**Comment by progrape** [comment]
这是因为`webpack-dev-server`为了安全，默认只绑定localhost的地址，你可以手动添加参数`--host 0.0.0.0`来允许通过你机器的IP来访问。可以修改`package.json`文件，使`npm start`的启动命令如下：

```json
{
    "scripts": {
        "start": "webpack-dev-server --devtool eval --progress --hot --colors --content-base example --host 0.0.0.0"
    }
}

```

**Comment by Joodysen** [comment]
改了package问题解决了，非常感谢大神，会持续关注项目的

**Comment by progrape** [comment]
不客气
