### ISSUE TITLE
按例子的格式写法报错，不知是否依赖版本的问题？

### ISSUE THREAD

**Issue by leochinacn** [weui/react-weui#103]
62 | class ActionS extends React.Component {

> 63 |      state = {
>      |                       ^
>   64 |          show:false,
>   65 |          menus:[{
>   66 |              label:'我的相机',

**Comment by n7best** [comment]
这个能再具体点吗 比如代码 以及npm版本和react版本

**Comment by zy308718320** [comment]
我也遇到了这个问题，应该是没有es7的支持，需要把state写在构造器里面
 constructor() {
    super();
    this.state = {
      show: false,
      menus: [{
        label: '拍照',
        className: 'customClassName',
        onClick: ()=> {

        }
      }, {
        label: '从手机相册中选择',
        className: 'customClassName',
        onClick: ()=> {

        }
      }],
      actions: [{
        label: '取消',
        className: 'customClassName',
        onClick: this.hide.bind(this)
      }]
    };
  }

**Comment by n7best** [comment]
嗯 这样写法是需要es7支持的 不过因自己的项目设定为准 不需要跟react-weui的格式一样
