### ISSUE TITLE
webpack报错

### ISSUE THREAD

**Issue by dreamcog** [weui/react-weui#104]
import “weui”

这一行报错：
错误如下：

ERROR in ./~/weui/dist/style/weui.css
Module parse failed: /Users/dreamcog/Site/c/site/static/js/checkin/node_modules/weui/dist/style/weui.css Unexpected token (6:5)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (6:5)

**Comment by n7best** [comment]
看 #61
