### ISSUE TITLE
引入Form组件为一个空对象

### ISSUE THREAD

**Issue by licanbluesea** [weui/react-weui#109]
import {Form,FormCell,Cell,CellHeader,CellBody,Label,Input} from 'react-weui';
console.log(Form)//object{}
console.log(FormCell)//undefined
请问这样引入有错吗？

这是引入的相关依赖
 "dependencies": {
    "history": "^1.13.0",
    "iscroll": "^5.1.3",
    "jquery": "^2.2.3",
    "loglevel": "^1.4.0",
    "object-assign": "^4.0.1",
    "react": "^0.14.8",
    "react-dom": "^0.14.8",
    "react-iscroll": "^1.0.1",
    "react-router": "^1.0.0",
    "react-weui": "^0.2.0",
    "reflux": "^0.3.0",
    "url-param-parser": "0.0.2",
    "url-params-helper": "^0.1.2",
    "weui": "^0.4.3"
  },

**Comment by n7best** [comment]
用的是babel 6?
