### ISSUE TITLE
引用weui样式，scrollTOP获取值失败，何解？

### ISSUE THREAD

**Issue by mingtian110** [weui/react-weui#110]
问题：
项目中用到react-weui ，使用到weui样式：
![qq 20160720164444](https://cloud.githubusercontent.com/assets/11565694/16980596/54fc055c-4e99-11e6-87cb-03c491b89e38.png)

在获取scrollTop时遇到一些问题：
当页面引用weui样式时，查看body的scrollTop值为0：
![qq 20160720164208](https://cloud.githubusercontent.com/assets/11565694/16980533/fcb939c8-4e98-11e6-91f3-81e99d458bb5.jpg)
控制台打印该值亦为0：

![qq 20160720164403](https://cloud.githubusercontent.com/assets/11565694/16980570/308c2aa8-4e99-11e6-9c93-f73a16e1775c.jpg)
r然后删除weui样式引用：
![qq 20160720164529](https://cloud.githubusercontent.com/assets/11565694/16980602/61f33cee-4e99-11e6-913c-55c95b837ebb.png)
再查看body的scrollTop值 显示正常：
![qq 20160720164615](https://cloud.githubusercontent.com/assets/11565694/16980618/7e4a10e8-4e99-11e6-997b-3936e753d4f3.png)
控制台打印该值，亦为正常：
![qq 20160720164650](https://cloud.githubusercontent.com/assets/11565694/16980634/9298ec22-4e99-11e6-8d17-b7d08bb4bcf2.png)
该如何解决？

**Comment by haibinyu** [comment]
这个要先看一下body里面的元素有没有定位（absolute或者fixed）的，看到内容被包到#content里面，#content没有问题？

**Comment by mingtian110** [comment]
刚才在elements的style窗口找到一个有反应的样式：overflow:hidden,
![qq 20160720170908](https://cloud.githubusercontent.com/assets/11565694/16981323/b1860f36-4e9c-11e6-9050-e1b9890f35e1.png)
取消该样式，就又可以打印了，找到该样式的文件所在地：
![qq 20160720171128](https://cloud.githubusercontent.com/assets/11565694/16981392/0386eb0c-4e9d-11e6-9424-53c53d964ade.jpg)
但是这个样式在weui.css中无法找到。

**Comment by mingtian110** [comment]
不好意思 看来是我弄错了 上面的那个样式在amazeui.touch.css里面找到了，项目中以weui为主,amazeui.touch的样式估计是打包的时候全塞到weui的样式里去了,问题已解决,谢谢.
