### ISSUE TITLE
日期选择器这些组件怎么调用呢

### ISSUE THREAD

**Issue by HiroBaby** [weui/react-weui#111]
有一些weui的组件，好像没有整合进去，请问我要怎样调用呢？

**Comment by n7best** [comment]
日期选择 你说的是jquery-weui的组件吗？

**Comment by HiroBaby** [comment]
你好，感谢你回复，比如说Date Picker，这个组件，在React里面怎么用呢

**Comment by n7best** [comment]
你说的原生的组件吗 weui里头的date picker就是用原生的 所以只要给Input 加个type="date"的属性就好了

**Comment by HiroBaby** [comment]
这种方法，我用过，但是在手机的浏览器上就没效果了，点不了

**Comment by n7best** [comment]
这个属于weui的问题 需要放到weui的issues那边
