### ISSUE TITLE
当页面较短时，ActionSheet显示不全

### ISSUE THREAD

**Issue by na57** [weui/react-weui#115]
手机上测试显示效果如下：ActionSheet下半截显示不出来。
![img_5415](https://cloud.githubusercontent.com/assets/3517150/17271403/0ff4f5ec-56ad-11e6-92c3-fd5b67bba5e0.PNG)
在微信开发者工具上显示正常：
<img width="376" alt="2016-07-30 11 20 48" src="https://cloud.githubusercontent.com/assets/3517150/17271412/35af60d8-56ad-11e6-96c8-d9e73c051dbf.png">

这个怎么解？

**Comment by n7best** [comment]
开发者工具可以连手机 debug看看那部分什么情况
