### ISSUE TITLE
Unknown Prop Warning

### ISSUE THREAD

**Issue by aximario** [weui/react-weui#116]
在我使用react-weui时，控制台报`warning`

我使用的是
* **react v15.2.1**
* **react-weui v0.4.0**

```
Warning: Unknown prop `switch` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

点击链接给我链接到了[Unknown Prop Warning](https://facebook.github.io/react/warnings/unknown-prop.html)页

原因是我使用的**Switch**组件会在`input`元素上加上非法的**switch**属性，希望能尽快修复，谢谢！

**Comment by aximario** [comment]
感谢关注此Issue

**Comment by pokka** [comment]
@aximario 修复代码已经合到了 develop( #107 ), 但是不知道什么时候合进 master...
可以先用[这个我的 build 版本分支](https://github.com/pokka/react-weui/tree/develop-with-build)(使用develop 分支的代码, 不确定是否有其他问题)

**Comment by aximario** [comment]
@pokka 额，好的，我还是先忍受一下等更新吧，不过已经知道接下来的版本里应该会修复此问题了，谢啦 :D
