### ISSUE TITLE
急：Form 表单如何提交如何获取其中input的各字段的值

### ISSUE THREAD

**Issue by Yhaojing** [weui/react-weui#122]
` <Form>
            <FormCell warn={isValidInput[0]} >
              <CellHeader>
                <Label>手机号</Label>
              </CellHeader>
              <CellBody>
                <Input type="tel" placeholder="输入手机号" />
              </CellBody>
              <CellFooter >
                <Icon value="warn" />
              </CellFooter>
            </FormCell>
          <FormCell>
              <Button onClick={this.handleSubmit}>登录绑定</Button>
            </FormCell>
          </Form>`
这样提交表单在handleSubmit 中怎么获取输入的手机号？

**Comment by maigoxin** [comment]
同问，我本来以为可以通过ref来解决。发现ref获取的是Input组件~  希望有结果了能通知一下

**Comment by haibinyu** [comment]
通过onChange事件。

**Comment by Yhaojing** [comment]
我不想通过ref取值，难道weui没有取值的方法吗？还有我是想在最后提交的时候获取表单值，不是在输入的时候获取

**Comment by n7best** [comment]
用state存值 onchange更新
可以看react form的推荐使用方法
https://facebook.github.io/react/docs/forms.html

**Comment by maigoxin** [comment]
onchange state的实现模式还是比较好理解。我这里有一个问题，这样的实现方式会不会导致dom被频繁的刷新呢？ react不是每一次state修改就有可能触发dom diff吗？

**Comment by n7best** [comment]
@maigoxin react刷新是很频繁的 如果怕影响整体可以单独组件上用shouldComponentUpdate来判断是否需要更新dom

**Comment by kala888** [comment]
有没有比较统一的解决方案类似于rc-form，集成rc-form，失败
