### ISSUE TITLE
请问下，Cell组件中的href如何替换为route的Link？

### ISSUE THREAD

**Issue by lzp819739483** [weui/react-weui#127]
我使用这样的写法：
```<Cell className="list_item" href={<Link to="/karman">a</Link>}>```
貌似是不好用的，请问有什么好办法

**Comment by n7best** [comment]
#92

**Comment by lzp819739483** [comment]
看到方法了。谢谢。我将Cell组件替换为了Link+样式。

**Comment by menthe** [comment]
请问如何替换呢？有没有参考？ @lzp819739483
