### ISSUE TITLE
Button class 名称不对

### ISSUE THREAD

**Issue by nxf** [weui/react-weui#136]
npm install weui react-weui --save后,使用Button做了个例子，发现css设置不对，都是类如weui_btn weui_btn_primary之类的名称，但实际上weui css的类是weui-btn这样的风格----即实际设置的类名是下划线，但是css中的是中划线。这是因为什么呢？

**Comment by n7best** [comment]
现在的react-weui版本是对应weui 0.4.x的 对应1.0.0的版本还没有发布

**Comment by n7best** [comment]
更新了下文档 0.4.x 需要使用
```
npm install react weui@0.4.3 react-weui --save
```
