### ISSUE TITLE
需要 Loading Toast

### ISSUE THREAD

**Issue by linkkingjay** [weui/react-weui#14]
[WeUI 的 Demo](http://weui.github.io/weui/#toast) 中是有 Loading Toast ，但是 React-WeUI 没有，看了一下代码只能传入一个 WeUI ICON ，但是 WeUI Toast 中的 loading 并不是一个标准 ICON 。

**Comment by progrape** [comment]
确实需要增加loading~

**Comment by linkkingjay** [comment]
:+1:
