### ISSUE TITLE
0.4.1版本FormCell Object.assign语法微信不支持

### ISSUE THREAD

**Issue by luqin** [weui/react-weui#144]

**Comment by n7best** [comment]
是用的npm bundle吗? 还是使用源码？最好发下使用的代码

**Comment by luqin** [comment]
使用的 npm bundle ，我的webpack里排除了编译node_modules，include 了 react-weui 就好了，会将Object.assign 再编译

**Comment by rockyLegond** [comment]
有没有Ｑ群一起学习react-weui?

**Comment by xughv** [comment]
升到0.4.1，在安卓微信平台测试时遇到包含Tab和Form组件页无法打开。

使用`babel-polyfill`可以使用，应该是引入Object.assign所致。

**Comment by luqin** [comment]
@xughv 
```
        test: /\.(js|jsx)$/,
        include: [constants.SRC_DIR, path.join(constants.NODE_MODULES_DIR, 'react-weui')],
        loader: 'babel-loader',
```

**Comment by progrape** [comment]
目前微信里面的 X5 是不支持 `Object.assign` ，需要 polyfill

**Comment by n7best** [comment]
和 #159 建议一起讨论
