### ISSUE TITLE
[0.4.1] SearchBar 清空按钮点击无反应

### ISSUE THREAD

**Issue by luqin** [weui/react-weui#148]
页面包含SearchBar和Radio按钮组。
SearchBar输入文字后，初始化时清空按钮正常；
SearchBar输入文字后，选择Radio项，点击清空按钮无反应。

**Comment by n7best** [comment]
有具体的代码吗？

**Comment by luqin** [comment]
在 0.4.1 版本：
https://github.com/weui/react-weui/blob/0.4.x/src/components/searchbar/searchbar.js#L91

1.0 版本
https://github.com/weui/react-weui/blob/master/src/components/searchbar/searchbar.js#L138
