### ISSUE TITLE
现在如何能用上1.0的组件

### ISSUE THREAD

**Issue by medolyWu** [weui/react-weui#149]
现在安装的是0.4.1，但是现在急需使用1.0的几个组件，请问该如何做

**Comment by n7best** [comment]
1.0还没发布到npm 还需要测试段时间 如果急用 那只能直接调用源码

**Comment by ilife5** [comment]
@medolyWu 可以尝试用源码，涉及到1.0样式，可以去weui里面找。

**Comment by progrape** [comment]
现在还在写测试用例和文档，还需要点时间

**Comment by leecz** [comment]
辛苦了，加油啊！

**Comment by ohmyauthentic** [comment]
@progrape 辛苦啦，预计还有多久发布1.0？
