### ISSUE TITLE
container和page的样式为什么要这么搞而不是直接把内容放到body里面？

### ISSUE THREAD

**Issue by ilife5** [weui/react-weui#150]
请教为什么要把container和page的样式去模拟body的行为，而不是直接把内容放到body里面？

```
.container {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    overflow: hidden;
}


.page {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    overflow-y: auto;
    -webkit-overflow-scrolling: touch;
    z-index: 1; // fix 滑动几次后可滚动区域会卡住的问题
}
```

**Comment by n7best** [comment]
这个是参照weui 样式的 
https://github.com/weui/weui/blob/master/src/example/example.less
有问题可以发issue到那边

关于使用react时候 尽量不要渲染内容到body:
React需要使用他渲染的node有全部的控制,body里头经常会出现其他框架和浏览器插件的内容，容易导致react无法掌控所有的node而导致出错

**Comment by ilife5** [comment]
感谢

我在那边找到了回答。

https://github.com/weui/weui/issues/1

期待你的1.0版本，我们现在已经在项目里面用了，一些功能用的源码，样式从weui里面扒出来了。
