### ISSUE TITLE
0.4.1版本，searchBar在ios真机上，取消、清除按钮，点击无效

### ISSUE THREAD

**Issue by cncowboy** [weui/react-weui#155]
0.4.1版本，searchBar在ios真机上，取消、清除按钮，点击无效

**Comment by n7best** [comment]
具体ios和微信版本？

**Comment by luqin** [comment]
微信web开发者工具上也一样，测试发现移除input的onBlur事件后，按钮可正常触发

**Comment by luqin** [comment]
可以参考 ant-design-mobile 的 Search Bar 组件：https://mobile.ant.design/components/search-bar/
