### ISSUE TITLE
建议: 使用 babel-runtime 替换 babel-polyfill

### ISSUE THREAD

**Issue by yahiousun** [weui/react-weui#159]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**
建议
**What is the current behavior? (现有状况)**
1. 不必要的polyfill, 打包了没有使用的模块 
2. 如果已经引用 babel-polyfill 会造成重复打包, ERROR in only one instance of babel-polyfill is allowed
**What is the expected behavior? （应有状况）**
使用 'babel-plugin-transform-runtime plugin', 只加载必要ES6模块

i.e. in ES6
```javascript
const config = Object.assign({}, {b: 1});
```
Output
```javascript
var _assign = require('babel-runtime/core-js/object/assign');
var _assign2 = _interopRequireDefault(_assign);

var config = (0, _assign2.default)({}, {b: 1});
```
**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**
React-weui版本 both 0.4.x && 1.0.x 
weui v0.4.3
系统 Android any X5内核

**Comment by n7best** [comment]
谢谢建议 的确强制性使用babel以及重复倒入是个问题

**Comment by luqin** [comment]
:+1:
