### ISSUE TITLE
使用CityPicker的时候引入不了，想问下有文档吗？

### ISSUE THREAD

**Issue by Sssnone** [weui/react-weui#160]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**

**What is the current behavior? (现有状况)**

**What is the expected behavior? （应有状况）**

**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**

**Comment by n7best** [comment]
组件还需要具体测试一下 暂时不能直接引用，有可能api也会改
