### ISSUE TITLE
[建议]Uploader整合一下JSSDK的api

### ISSUE THREAD

**Issue by 634750802** [weui/react-weui#161]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**
建议
**What is the current behavior? (现有状况)**
Uploader获取的是图片文件的信息
**What is the expected behavior? （应有状况）**
希望使用Uploader能获取到[JSSDK](https://mp.weixin.qq.com/wiki)中wx.chooseImages获取的id
**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**
react-weui 0.4.x

**Comment by n7best** [comment]
这个之后可以加入到插件里头 不过正式组件和jssdk绑定感觉不是很好

**Comment by 634750802** [comment]
我觉得也不太适合 但是用JSSDK的时候就相当于把Uploader重新写了一遍 现在并没有想到比较好的解决方法
