### ISSUE TITLE
引入样式不起作用weui跟react-weui的样式都导入了，但是不起作用

### ISSUE THREAD

**Issue by Qukoko** [weui/react-weui#165]
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import WeUI from 'react-weui';
import logo from './logo.svg';
import 'weui';
import 'weui/dist/style/weui.css';
import './App.css';
import 'react-weui/lib/react-weui.min.css'
const { Button } = WeUI;

**Comment by n7best** [comment]
你用的是 create react app 吗。只需要 import weui 和 import react weui 那两行 我测试了下是可以的  两个包都装了？
