### ISSUE TITLE
 react-boilerplate 中引入react-weui，从0.4.3升级到1.0后编译报错

### ISSUE THREAD

**Issue by irisme** [weui/react-weui#169]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**
bug
**What is the current behavior? (现有状况)**

**What is the expected behavior? （应有状况）**

**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**

**Comment by n7best** [comment]
测试全新安装使用没问题 报什么错了 还是有些[升级改动](https://github.com/weui/react-weui/blob/master/CHANGELOG.md)没改?

**Comment by irisme** [comment]
@n7best 在react-boilerplate 中只是升级了weui和react-weui的版本，引了react-weui的css文件，然后运行react-boilerplate的编译脚本
![e7e1859a-00c0-4a5a-bef0-8d76771a2e59](https://cloud.githubusercontent.com/assets/3959962/21375250/38d9fa40-c767-11e6-97ae-9230f0d96969.png)

**Comment by irisme** [comment]
@n7best 我直接在新的项目中集成react-boilerplate 和react-weui，只用到了react-weui的Botton组件，在0.4.1的版本下编译后的项目没有问题，升级到1.0.3之后编译报错，测试项目地址[https://github.com/irisme/react-boilerplate-test](url)

**Comment by n7best** [comment]
这个是webpack的引用方面的问题, 类似于 https://github.com/webpack/webpack/issues/959

暂时的解决方法你可以把[这行](https://github.com/irisme/react-boilerplate-test/blob/master/internals/webpack/webpack.prod.babel.js#L28)去掉

**Comment by irisme** [comment]
解决了，太感谢了 @n7best
