### ISSUE TITLE
Grid / Grids 标签包裹

### ISSUE THREAD

**Issue by TimonPeng** [weui/react-weui#176]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**

建议

**What is the current behavior? (现有状况)**

`https://github.com/weui/react-weui/blob/master/src/components/grid/grid.js#L36`

Grid 采用了 `<a>`，链接参数通过：`href: '/admin'` 方式提供，这样无法使用 react-router 的 Link 和 Index Link包裹 `<Grid />`，a 标签无法包裹 a 标签，无法进行路由热跳转。

**What is the expected behavior? （应有状况）**

是否采用 `<div>` 更好？

**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**

"react-weui": "^1.0.3",
"weui": "^1.1.0"

**Comment by n7best** [comment]
的确 可以把有链接性质都改成cell组件那样的 直接传组件替代 这样也不会仅限于react-router了 之前没改全面

**Comment by n7best** [comment]
related to #213
