### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by git-lt** [weui/react-weui#178]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**

**What is the current behavior? (现有状况)**
vendor.bundle.js报错
```bash
vendor.bundle.js:9670 Warning: 
You are manually calling a React.PropTypes validation function for the `path` prop on `Route`. 
This is deprecated and will not work in production with the next major version. 
You may be seeing this warning due to a third-party PropTypes library.
 See https://fb.me/react-warning-dont-call-proptypes for details.
```
**What is the expected behavior? （应有状况）**

**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**

**Comment by n7best** [comment]
这个是个warning警告 是因为使用旧版本的react-router导致的 已经计划中升级使用版本了 本身组件库并不会使用到react-router
