### ISSUE TITLE
actionsheet使用问题

### ISSUE THREAD

**Issue by ITJaye** [weui/react-weui#18]
https://github.com/weui/react-weui/blob/master/docs/actionsheet.md
actionsheet在使用时除了设置state.show为true外，还需要设置actionsheet的state属性active为true（this.refs.actionsheet.state.active = true;）才能正常弹出底部按钮

**Comment by n7best** [comment]
能举个例子吗 应该是不需要的 actionsheet本身是stateless的 只需要通过上级配置属性给它就好了

**Comment by n7best** [comment]
@ITJaye  @progrape 测试了一下，的确是这样，npm 的版本和git上面的源码不符合

**Comment by progrape** [comment]
@ITJaye @n7best 感谢指出，npm上的包会比github上滞后一点。@n7best 更新的文档麻烦发个PR过来？:grin:
