### ISSUE TITLE
PullToRefresh组件不存在

### ISSUE THREAD

**Issue by xuanheScript** [weui/react-weui#180]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**
bug
**What is the current behavior? (现有状况)**
PullToRefresh组件不存在
**What is the expected behavior? （应有状况）**
PullToRefresh组件存在
**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**
react-weui 版本1.0.3  weui 版本1.1.0

**Comment by xuanheScript** [comment]
![image](https://cloud.githubusercontent.com/assets/19216775/21561296/e24a3a00-cea5-11e6-9f5a-c33a1cb1ddad.png)

**Comment by n7best** [comment]
你好 master branch属于在开发版本 并没有根正式版本对其 可以看下tag里头1.0.0的组件

**Comment by jonahfang** [comment]
@n7best, 我package.json中写了1.0.4,`npm i` 后也更新了，看到node_modules中也有 ptr.js，为何还是不能用PullToRefresh呢？

**Comment by jonahfang** [comment]
我的问题解决了，不存在此问题。
