### ISSUE TITLE
希望InfiniteLoader加载完毕的tips可以定制

### ISSUE THREAD

**Issue by freefishz** [weui/react-weui#183]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**
feature
**What is the current behavior? (现有状况)**
现在只能显示`No Data`
**What is the expected behavior? （应有状况）**
可以通过传入props，显示中文或其他自定义信息
**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**
1.0.4, chrome 浏览器

**Comment by n7best** [comment]
可以传 loaderDefaultIcon 来改试试

**Comment by freefishz** [comment]
刚看了一下源代码，明白啦。可以把这个issue关掉了。如果文档说明的例子里能加上一个例子，可能会更好。anyway，thx.
