### ISSUE TITLE
[Q&A]今天阅读了源代码，发现有三种风格

### ISSUE THREAD

**Issue by ryouaki** [weui/react-weui#186]
发现这些代码有3种风格，从component的定义方式来看，有函数式，有es6，继承react.component。也有直接import { component }，然后继承component的。感觉很怪异。

很多地方使用了findDomNode，其实使用ref以后就可以在组件mount以后直接从this.refs中得到对应的dom。为何还要使用该api去取？是历史原因？

**Comment by n7best** [comment]
是啊 一开始是 react 0.14rc 还没那么完善

**Comment by ryouaki** [comment]
哦，我是最近半年才开始使用reactjs，看到weui以后感觉欣喜，阅读了源码，学习一下。

目前weui应该是主要面对微信公众号这个使用场景而开发的吧？但是在我看来weui这个库应该可以针对所有移动端平台而不仅仅局限于wechat，从之前一个issue提到不想把jssdk集成进来就是有这方面考虑吧？而且性能要比antd高很多。很想在下一个移动端项目使用一下。

不知道有什么建议吗？
