### ISSUE TITLE
1.0版本不支持服务器端渲染？

### ISSUE THREAD

**Issue by threem0126** [weui/react-weui#191]
源码中看到，对浏览器有判断：
window.navigator.userAgent

导致服务器端渲染失败

**Comment by n7best** [comment]
可以用测试版本 有修改 1.0是有这个bug

**Comment by threem0126** [comment]
好的

PS：测试版本预计何时发布？：）

**Comment by gooddaddy** [comment]
请问这个问题解决了吗，如何获取测试版？
