### ISSUE TITLE
扫二维码的demo地址被微信封禁了！

### ISSUE THREAD

**Issue by bigzs** [weui/react-weui#193]
扫二维码的demo地址被微信封禁了！

**Comment by n7best** [comment]
我试了下还是可以 具体是啥封禁信息?

**Comment by bigzs** [comment]
![qq 20170203102138](https://cloud.githubusercontent.com/assets/25221782/22577119/dbe91904-e9fa-11e6-9aa8-2cac78563fa9.png)
![img_0048](https://cloud.githubusercontent.com/assets/25221782/22577124/df7814bc-e9fa-11e6-917e-1e3e16a13ece.PNG)
已停止访问该网页。

**Comment by bigzs** [comment]
@n7best

**Comment by progrape** [comment]
解决了~
