### ISSUE TITLE
下拉刷新和上拉加载一起使用bug

### ISSUE THREAD

**Issue by Allen-vip** [weui/react-weui#198]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**

**What is the current behavior? (现有状况)**

**What is the expected behavior? （应有状况）**

**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**

**Comment by Allen-vip** [comment]
上拉加载所有数据之后，在进行下拉刷新，上拉加载的状态 (这个时候显示已经加载完成) 无法重置。

**Comment by Allen-vip** [comment]
选择在上拉刷新之后，重新加载下组件。。貌似只有这样重置状态了。

**Comment by liulingli** [comment]
怎么重新加载组件的呢
