### ISSUE TITLE
[Security issue on Wechat] WeChat indicated as not safe to view

### ISSUE THREAD

**Issue by haxpor** [weui/react-weui#199]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**
It's security issue.

**What is the current behavior? (现有状况)**
It shows me the following image indicating that it's not safe.

![img_3368](https://cloud.githubusercontent.com/assets/673757/22941702/871ecdda-f321-11e6-9ea0-347577c59187.PNG)

Then it ask me 3 questions to submit and regain my access to the site. But as I'm not Chinese citizen, I don't have ID to provide to them to regain access.

**What is the expected behavior? （应有状况）**

If I scan the qr code at the front page of this repository, it should direct me to the demo.

**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**
I'm on iPhone 6S 10.3. I scan qr code on front page of this repository (I'm not sure which version of react-weui it is).

**Comment by n7best** [comment]
thanks, @progrape can you take a look?

**Comment by haxpor** [comment]
@n7best Thanks for prompt reply. Long before, I can access without such error. I think before Mini program got introduced.
