### ISSUE TITLE
真机测试 苹果5S IOS8.2 Picker组件无法滑动

### ISSUE THREAD

**Issue by peters1990** [weui/react-weui#200]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**

**What is the current behavior? (现有状况)**

**What is the expected behavior? （应有状况）**

**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**

**Comment by n7best** [comment]
#190

**Comment by 495640129** [comment]
react-weui@1.0.3,weui@1.1.0 华为荣耀4C

**Comment by 495640129** [comment]
#222

**Comment by TaoMeiLi** [comment]
react-weui@1.0.3 也有这个问题，华为和苹果可以滑动，但是选中的不是所选的，第一项和第二项滑不下来
