### ISSUE TITLE
本地图片路径怎么都写不对，麻烦帮忙看下

### ISSUE THREAD

**Issue by files3** [weui/react-weui#205]
dva new一个项目，初始页面那个图片都有
为什么在同级的js文件就不行

<img width="1040" alt="wx20170217-160353 2x" src="https://cloud.githubusercontent.com/assets/15240870/23057350/b7ebc598-f52a-11e6-88f2-08631045dda4.png">

**Comment by n7best** [comment]
这个应该是环境设置问题

**Comment by files3** [comment]
已搞定
