### ISSUE TITLE
组件是否考虑加透出className这个props，不然重置样式不科学

### ISSUE THREAD

**Issue by aniwei** [weui/react-weui#206]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**

**What is the current behavior? (现有状况)**

**What is the expected behavior? （应有状况）**

**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**

**Comment by n7best** [comment]
谢谢, 能具体点吗, 哪个组件需要className 应该都加上了, 可能有疏忽了
