### ISSUE TITLE
react-weui有路由的相关文档吗？有的时候用组件路由跳转不知如何下手

### ISSUE THREAD

**Issue by files3** [weui/react-weui#208]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**

**What is the current behavior? (现有状况)**

**What is the expected behavior? （应有状况）**

**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**react-weui=1.0.3，weui=1.1.0

在用到react-weui时，有的组件是用href，
如下图，用到了Grids组件，但是这个路由跳转就很迷茫了，href又不能用
![wechatimg9](https://cloud.githubusercontent.com/assets/15240870/23118543/7a65849a-f78f-11e6-8868-2f8e2d86a3ee.jpeg)

**Comment by n7best** [comment]
cell组件是可以传组件进去的 grids 疏忽了这点 之后会修正

**Comment by files3** [comment]
@n7best 好的，静等修正，目前项目正规划使用

**Comment by files3** [comment]
panel的href可以吗？嵌套Link虽然可以跳转，但是会有警告说a不能嵌套
<img width="1036" alt="wx20170221-104640 2x" src="https://cloud.githubusercontent.com/assets/15240870/23148863/11633552-f823-11e6-8f8f-85461cfe8cf6.png">

**Comment by n7best** [comment]
`PanelFooter`之类的把href属性去掉就会自动用div不用a了 现在暂时应该只有一两个组件是像Cell可以直接传组件进去代替的

**Comment by files3** [comment]
@n7best 好的谢谢

**Comment by ettingshausen** [comment]
这个问题是在 #213 解决了么？
`1.1.3` 版本 按照 @haxpor 给出得例子， `to` 貌似不起作用。
```js
const gridData = Array(9).fill({
    icon: <FaReact size={32}/>,
    label: 'Grid',
    to: "/device",
})
```
渲染的结果类似：
```js
<a class="weui-grid" to="/device">...</a>
```
