### ISSUE TITLE
在index.html页面link，

### ISSUE THREAD

**Issue by files3** [weui/react-weui#209]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**

**What is the current behavior? (现有状况)**

**What is the expected behavior? （应有状况）**

**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**1.0.3   weui=1.1.0

不想用link链接一些额外的cdn形式的css样式，因为在没有网络的情况下，cdn加载不出来导致整个页面加载不出来，
想下载到本地使用css样式，但是link href本地地址就会出错样式不能用，在less里面@import说模块没找到，把link href地址改成cdn的就管用了，想问下怎么回事？

**Comment by ryouaki** [comment]
想引入css需要在entry的jsx文件import './file.css'

在index.html中link引入的css文件，需要指向文件的相对路径。或者server上的地址。

**Comment by files3** [comment]
@ryouaki   是的，我下载到本地在es6里用了import ‘’引入是可以的

**Comment by ryouaki** [comment]
@files3 一般来讲，我们都是在entry文件import引入css的，然后在webpack执行的时候，会自动将你引入的css或者less添加在html的头。

你可以下载安装一个facebook的脚手架，生成一个空工程。看一看。

对于css的打包，就要自己研究一下webpack的css打包loader了。

**Comment by files3** [comment]
@ryouaki facebook的脚手架？你是说的react吧，我用vue-cli  new的一个vue项目，要是react的话我用dva

**Comment by ryouaki** [comment]
是。我是用react。vue不了解。
