### ISSUE TITLE
Grid should also work properly with URL as set from `react-router`

### ISSUE THREAD

**Issue by haxpor** [weui/react-weui#212]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**
Request a feature. But it can be regarded as a bug too.

**What is the current behavior? (现有状况)**
Grid when click will take you to the target URL if you set `href`. But for the case if such target URL is as part of `react-router`'s URL, then it won't work when you build react into production build. It returns 404.

**What is the expected behavior? （应有状况）**
It should work the same even such URL is as part of `react-router`.

**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**
React-weui: `1.0.3`
weui: `1.1.0`

**Comment by n7best** [comment]
related to #208
