### ISSUE TITLE
请教个问题，怎么取组件里面的值呀

### ISSUE THREAD

**Issue by xiaowang1314** [weui/react-weui#217]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**

**What is the current behavior? (现有状况)**

**What is the expected behavior? （应有状况）**

**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**

**Comment by xiaowang1314** [comment]
取ui组件的值是一定要用事件获取嘛，有没其他方便点的方法，请大神告知

**Comment by ruoru** [comment]
你用的什么组件？picker还是citypicker。这两个都有回调方法，你可以看一下[demo](https://weui.github.io/react-weui/#/?_k=wkm4ra)对应代码是[picker_index](https://github.com/weui/react-weui/blob/master/example/pages/picker/index.js)
