### ISSUE TITLE
1.0.3 react-weui 内没有找到infiniteLoader这个组件

### ISSUE THREAD

**Issue by wishingweed** [weui/react-weui#224]
您好我安装了1.0.3的react-weui
然后我发现component里面好像没有Infiniteloader这个组件，我想知道是从这个包里删除了还是移动到什么其他地方了，谢谢

**Comment by ityao** [comment]
是啊, 郁闷啊, 什么时候能发布新版本呢

**Comment by wbye** [comment]
npm i  react-weui@1.0.4  试下1.0.4尝鲜版

**Comment by NicholasNC** [comment]
同问，为什么会缺失部分组件？
