### ISSUE TITLE
react-weui中的tab怎么让导航栏滑动？

### ISSUE THREAD

**Issue by 310731483** [weui/react-weui#236]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**

**What is the current behavior? (现有状况)**

**What is the expected behavior? （应有状况）**

**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**

**Comment by kala888** [comment]
@310731483  时间挺长的了 有没有解决？

**Comment by 310731483** [comment]
已解决。谢谢

**Comment by kala888** [comment]
@310731483 能不能分享一下解决方案呢，我也遇到这个问题，可以滑动，但是下面的body也跟着滑动了
