### ISSUE TITLE
React is not defined ？

### ISSUE THREAD

**Issue by zoeblow** [weui/react-weui#249]
为啥我项目中使用react-weui的时候 控制台就会报 **Uncaught ReferenceError: React is not defined** ，项目的控制台是没有报错的，但是浏览器的控制台就报错，试了好几次还是存在这个问题。

**Comment by SwordsmanYao** [comment]
我的也是这样
![bug](https://user-images.githubusercontent.com/20725188/28458742-6b03c7c6-6e3d-11e7-947c-f7572f3e75cd.png)

**Comment by menzil** [comment]
类次的问题，待解决。

**Comment by SwordsmanYao** [comment]
能具体解释下吗   怎样可以避免这个问题   我只是想让代码跑起来    还是有其他使用的方式不会出现这个问题

**Comment by n7best** [comment]
大家npm是什么version npm安装的还是浏览器调用的。应该是调用到了浏览器版本

**Comment by SwordsmanYao** [comment]
`npm install weui@1.1.0 react-weui --save`
这个

**Comment by SwordsmanYao** [comment]
我在react官方提供的demo（create-react-app）下安装也会有这个问题

**Comment by menzil** [comment]
@n7best macOS sierra : 10.12.6, nodejs: v6.10.2, npm: 3.10.10 , 我的都是npm安装的。是昨天开始出这样的问题。

**Comment by younes200** [comment]
Hi,
Event with `webpack.ProvidePlugin` to export React and ReactDOM, the issue still the same :
```
new webpack.ProvidePlugin({
      React: 'react',
      ReactDOM: 'react-dom'
    }),
```

```
import { Button } from 'react-weui'
console.log(Button) // returns undefined
```

Also the css file path in documentation is wrong too, the correct one : 
`import 'react-weui/build/dist/react-weui.css'`

**Comment by zoeblow** [comment]
@younes200 Why is this?

**Comment by minooo** [comment]
@n7best 楼上说的没错，现在必须 `import { Button } from 'react-weui/build/packages'`引用才没有问题，按照官网的 `import { Button } from 'react-weui'` 完全错误，这个明显严重的问题请尽快解决（发布新版本都不带测试的么你们？）

**Comment by chuncui0207** [comment]
+1

**Comment by n7best** [comment]
@minooo 疏忽了，测试时候用的网页环境所以没有问题😅
