### ISSUE TITLE
Uploader组件在IOS上无法选择照片，直接打开了相机

### ISSUE THREAD

**Issue by lifeipengdev** [weui/react-weui#251]
bug

Uploader组件在IOS上无法选择照片，直接打开了相机，在Android上正常

应该同时要支持ios/android

使用的版本如下
"react": "^15.6.1",
"react-weui": "^1.1.3",
"weixin-js-sdk": "^1.2.0",
"weui": "^1.1.0"

IOS手机为10.3.2
微信版本是6.5.12

**Comment by n7best** [comment]
@lifeipengdev 这个是`ios 10.3.1`之后对Input做的修改 可以试下在给uploader加上`catpure={false}`这个属性

**Comment by lifeipengdev** [comment]
已经解决了，感谢答复

**Comment by n7best** [comment]
i think you could do something like 
```
<Uploader capture={ !(window.navigator.platform === 'iPhone') } />
```

**Comment by youngjuning** [comment]
为什么不更新文档啊，大哥们
