### ISSUE TITLE
create-react-app  后的初始文件 `npm install weui@1.1.0 react-weui --save`  装入 `weui`后项目跑不起来

### ISSUE THREAD

**Issue by jiexishede** [weui/react-weui#253]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**
bug
**What is the current behavior? (现有状况)**
使用`create-react-app my-app` 创建的脚手架新项目, 执行 `npm install weui@1.1.0 react-weui --save1` 后跑步来.  
**What is the expected behavior? （应有状况）**

**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**

**Comment by jiexishede** [comment]
我是用 create-react-app 装了文件后, 在装一个其它的库还是不能跑.很可能是 `create-react-app` 这个教授架的问题.

**Comment by n7best** [comment]
我有测试create-react-app，具体是出现什么错误

**Comment by jiexishede** [comment]
You are using npm 5. At the moment it has many issues.

I recommend to downgrade to npm 4 and try again:

npm install -g npm@4

rm -rf node_modules
rm package-lock.json
npm install
If it doesn't help check your internet connection. This looks like an issue with your network:

getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443 .
