### ISSUE TITLE
会出react-native版的吗？

### ISSUE THREAD

**Issue by JerroldLee** [weui/react-weui#26]
会出react-native版的吗？

**Comment by progrape** [comment]
我们暂时没有计划出，不过已经有同学在 npm 注册了 [react-native-weui](https://www.npmjs.com/package/react-native-weui) 模块了。 @n7best 有什么计划没有？

**Comment by n7best** [comment]
暂时想等react-weui组件完善点再弄

**Comment by huliyou** [comment]
我打算开发weui的RN，能合并到项目群里么

**Comment by progrape** [comment]
@huliyou 很欢迎你开发。你可以先开发起来，这边加个链接过去，后面再视情况是否加到这里来~~

**Comment by progrape** [comment]
@huliyou 补充一下，视觉稿可以参考这里  https://github.com/weui/weui-sketch
