### ISSUE TITLE
组件增加需求

### ISSUE THREAD

**Issue by JerroldLee** [weui/react-weui#27]
这一套UI库挺完善的，http://m.sui.taobao.org/components/ 。 如果这些都有了，那么开发一个webapp就很方便了，希望能够在weui也实现，这样将大大方便我们这些微信开发者

**Comment by progrape** [comment]
@JerroldLee react-weui 的组件是跟着 [weui](https://github.com/weui/weui) 走的，要等那边有了之后才会跟上~
