### ISSUE TITLE
请问有没研发进度，想了解下。

### ISSUE THREAD

**Issue by memotail** [weui/react-weui#3]
如题，项目可能会用，谢谢。

**Comment by tindytian** [comment]
已经有人自己开搞了，参考[这里](https://github.com/n7best/react-weui)

**Comment by progrape** [comment]
#2

**Comment by n7best** [comment]
我的那个repo也转向这里，统一贡献

**Comment by progrape** [comment]
期待贡献~

**Comment by tlightsky** [comment]
现在还是差一些控件的吧，
react-weui现在接受pr吗

**Comment by progrape** [comment]
@tlightsky 接受pr，bug fix，改进、增加组件等都欢迎。不过改进和新增组件，建议先开issue讨论，确认之后再提交~

**Comment by tlightsky** [comment]
好的

**Comment by lzcmaro** [comment]
感觉push页面这样的组件可以加一下

**Comment by progrape** [comment]
@lzcmaro “push页面”组件是指？

**Comment by lzcmaro** [comment]
@progrape 类似于用jquery.fn.load()加载页面，支持动画。我跑了下weui，发现里面还没有。这段时间我刚好在弄ratchet的react版本，也有关注weui。希望有机会贡献一下

**Comment by progrape** [comment]
暂时想象不到:joy: ，你有空可以fork一份弄个demo看看，效果ok的话欢迎贡献给WeUI~~

**Comment by n7best** [comment]
#35
