### ISSUE TITLE
需要的react版本最低是多少

### ISSUE THREAD

**Issue by simhare** [weui/react-weui#300]
**Do you want to request a *feature* or report a *bug* (建议还是bug) ?**
Bug
为什么有这两行报警
npm WARN react-weui@1.1.3 requires a peer of react@0.14.x || ^15.0.0-0 || 15.x but none is installed. You must install peer dependencies yourself.
npm WARN react-weui@1.1.3 requires a peer of react-dom@^0.14.x || ^15.0.0-0 || 15.x but none is installed. You must install peer dependencies yourself.

我用的是16
"react": "^16.8.3",
"react-dom": "^16.8.3",

**What is the current behavior? (现有状况)**

**What is the expected behavior? （应有状况）**

**Which versions of React-weui, weui, and which OS and device are affected by this issue? (React-weui版本 weui版本 机型和系统)**

    "weui": "^1.1.0",
    "weui.js": "^1.1.4"

**Comment by z2014** [comment]
之前兼容的react版本是15.0.0，后面我们会升级react版本，目前16.8.3是可以的
