### ISSUE TITLE
Form Proposal

### ISSUE THREAD

**Issue by yjcxy12** [weui/react-weui#31]
新增4个组件: Form, FormCell, Input, Label

Form:
- props: none
- className: weui_cells, weui_cells_form

FormCell:
- props: vcode(bool), warn(bool)
- className: weui_cell, weui_vocde(vcode), weui_cell_warn(warn)

Input:
- props: defaultValue
- className: weui_input
- remark: 没有children, defaultValue加到attribute

Label:
- props: none
- className: weui_label

Discussion:
- 是否把Form和FormCell整合到一起

TODO:
- add tests after approval of idea
- add docs

具体code请看 #32

**Comment by n7best** [comment]
Form的本生和Cells只是差一个属性 整合一起比较好， FormCell应该是可以和input,label整合一起的

**Comment by progrape** [comment]
@n7best FormCell 和 input label 整合在一起，具体是指？

**Comment by n7best** [comment]
@progrape 因为我看Input和weui_label在 weui 只有form的时候才会用到. 这个FormCell的目的我看到也是针对普通input的，所以感觉可以变为里头的属性。 那不然每一个element都要弄一个component

**Comment by progrape** [comment]
FormCell 还要考虑单选框、复选框，而单选框复选框的 icon ，没有规定一定要在左边还是在右边，如果通过属性来描述，可能需要额外的属性来描述位置，没有直接用 children 来的直观。

**Comment by n7best** [comment]
单选复选的大属性(weui_cells_checkbox,weui_cells_radio)已经被绑架到weui_cells. 选择cell的input左右(weui_select_before,weui_select_after)也被捆到weui_cell上面 如果只用单纯的FormCell,children里头加上input, 不通过属性,children里头怎么设置上级的class

**Comment by progrape** [comment]
确实被捆绑了，单独把单选框、复选框拎出来也不是个东西 :joy:

**Comment by progrape** [comment]
其实理想的情况是，Cells、Cell 是独立的组件，单选框、复选框、选择、文本域、开关本身可以独立存在，使用的时候放在 Cells、Cell 里面。然而现在有的被绑到 Cells，有的被绑到 Cell。

**Comment by n7best** [comment]
嗯 的确是应该那个样子的 不过这个理想情况是基于react这种想法 单纯css的weui原来那样也没错

**Comment by progrape** [comment]
FormCell 如果和 Input、Label 整合在一起，通过属性传递，还有验证码和报错的情况，那么最复杂的情况下，使用方式将会：

```jsx
<form>
    <FormCell label="姓名" input=input vcode=img error />
</Form>
```

**Comment by yjcxy12** [comment]
Form和Cells只差了一个weui_cells_form。 不过我认为Form是一个很常见的组建，有必要做个单独的Component.
目前weui_label和weui_input只用于form里，但用户使用时应可以不使用form而使用input和label以做到自定义样式，所以建议作为单独的组件，更加灵活。

**Comment by n7best** [comment]
对的 可是weui默认的几个input 比如checkbox, radio, select都是需要在weui_cells上加额外class的,单独组件最好是不需要依赖其他组件比较好.

推荐给Form加些属性 比如 checkbox, radio, select.  
那不然之后要加FormsCheckbox, FormsRadio, FormsSelect

**Comment by n7best** [comment]
Form.js 的class应该叫Form？现在是cells感觉重名不好

**Comment by yjcxy12** [comment]
@n7best 写错了，已纠正。
