### ISSUE TITLE
React 16.9 reports the security: Warning: A future version of React will block javascript

### ISSUE THREAD

**Issue by ettingshausen** [weui/react-weui#320]
https://github.com/weui/react-weui/blob/232fb9421f715d9c50bcc7a1b0a989e6371f3721/src/components/dialog/dialog.js#L59  

issue at facebook/react#16382.  

Solution:
https://github.com/facebook/react/issues/16382#issuecomment-607252694

**Comment by z2014** [comment]
fixed
