### ISSUE TITLE
什么时候能把 tabbar panel 这些更新上来？

### ISSUE THREAD

**Issue by Yunlong2cn** [weui/react-weui#45]
有没有计划什么时间更新 tabbar panel 这样的，还是已经更新了，我没找到呀？我看 weui 里早就有这UI的呢

**Comment by n7best** [comment]
更新了下，在developer branch可以找到

**Comment by Yunlong2cn** [comment]
@n7best 好的，我更新看一下，不知道这些里面还会再更新吗？可以应用到生产环境吗？

**Comment by n7best** [comment]
tab, search bar还需要写测试, 过几天应该会更新好.

**Comment by iyoukeyyewei** [comment]
weui更新到0.4.0了，这里的什么时候能够跟上啊

**Comment by iyoukeyyewei** [comment]
什么时候更新到weui 0.4.0啊

**Comment by n7best** [comment]
#64

**Comment by yuan1995913** [comment]
@n7best 您好，请问developer branch在哪里能找到
