### ISSUE TITLE
Stateless Functional Components ?

### ISSUE THREAD

**Issue by RoberMac** [weui/react-weui#49]
為什麼不用 [Stateless Functional Components](https://facebook.github.io/react/docs/reusable-components.html#stateless-functions) ?

**Comment by n7best** [comment]
谢谢建议, 之前有用到, 后来写的时候应该是为了统一syntax，现状下stateless components并没有被优化 (React 0.15 RC 也没有提到优化这件事情).  

stateless components没有shouldComponentUpdate事件所以每次更新都会被重新render一次.

不过之后简单的component应该会都转stateless.

**Comment by RoberMac** [comment]
現在全部的 component 也沒用到 `shouldComponentUpdate` 吧？抑或說將來要用到？

不過也沒關係，[HoC](https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775) 不也可以控制是否重新 render 的問題麼？而且更加 reusable。

**Comment by n7best** [comment]
嗯是不错，我个人也比较偏向stateless的,  不过PR时候还是为了符合其它组件的格式.

**Comment by RoberMac** [comment]
比如：
```jsx
// src/components/HoCs/ReRender.jsx
import React from 'react';
import classNames from 'classnames';
import shallowCompare from 'react-addons-shallow-compare';

export default ComposedComponent => class extends React.Component {
    shouldComponentUpdate(nextProps, nexState) {
        return shallowCompare(this, nextProps, nextState);
    }
    render() {
        return <ComposedComponent {...this.props} {...this.state} />;
    }
}
```

```jsx
// src/components/Icon/Icon.jsx
import React from 'react';
import classNames from 'classnames';

import ReRender from '../HoCs/ReRender.jsx';

class Icon extends React.Component {
    ...
}

export default ReRender(Icon);
```

**Comment by RoberMac** [comment]
就目前而言，符合其它组件的格式是好事。
希望未來用到吧。

**Comment by progrape** [comment]
@RoberMac @n7best 感谢两位的讨论和建议，我们在下一个版本可以考虑使用这种方式~
