### ISSUE TITLE
Confirm 和 Alert 的区别？

### ISSUE THREAD

**Issue by holymonson** [weui/react-weui#50]
`dialog` 中  `Confirm` 和 `Alert` 的区别似乎只是内容左对齐或居中的样式不同？统一成 `Dialog` 然后加个 `style` 参数会更简单么？

**Comment by progrape** [comment]
@holymonson 一开始不用 style 的方式，主要是考虑到 weui 那边有定义好的 class 能用，就直接用了。不过你的建议也很好，考虑采用，谢谢
