### ISSUE TITLE
ActionSheet 的menus,actions 应该允许传入自定className

### ISSUE THREAD

**Issue by p2227** [weui/react-weui#51]
我看了一下源代码
```
<div key={idx} {...others} className={className}>{label}</div>
```
这里唯独排除了className，似乎需要有像  https://github.com/weui/react-weui/pull/17 那样的处理

**Comment by progrape** [comment]
ActionSheet 有什么场景需要传入 classname 控制样式不？

**Comment by p2227** [comment]
@progrape  是一个选择的菜单，用来标识当前用户选中的那个选项。比如字典项是1，2，3，用户当前选中的是2，那么弹出的时候希望2是高亮的用来提醒用户。

**Comment by progrape** [comment]
ActionSheet 并没有对某些项进行高亮的设计，都是并列的操作，所以不太推荐对某些项进行特殊处理。所以这个需求暂时 hold 住吧，如果有更多的场景需求，再考虑加入~

**Comment by p2227** [comment]
哦，好的
