### ISSUE TITLE
webpack: bundle is now VALID.

### ISSUE THREAD

**Issue by hubinjie** [weui/react-weui#52]
请问一下这是什么问题？

ERROR in ./~/react-router/lib/Router.js
Module not found: Error: Cannot resolve module 'history/lib/createHashHistory' in /Users/hubinjie/Documents/app/html5/react/react-weui/node_modules/react-router/lib
 @ ./~/react-router/lib/Router.js 23:35-75

ERROR in ./~/react-router/lib/useRoutes.js
Module not found: Error: Cannot resolve module 'history/lib/Actions' in /Users/hubinjie/Documents/app/html5/react/react-weui/node_modules/react-router/lib
 @ ./~/react-router/lib/useRoutes.js 15:25-55

ERROR in ./~/react-router/lib/useRoutes.js
Module not found: Error: Cannot resolve module 'history/lib/useQueries' in /Users/hubinjie/Documents/app/html5/react/react-weui/node_modules/react-router/lib
 @ ./~/react-router/lib/useRoutes.js 17:28-61

ERROR in ./~/react-router/lib/match.js
Module not found: Error: Cannot resolve module 'history/lib/createMemoryHistory' in /Users/hubinjie/Documents/app/html5/react/react-weui/node_modules/react-router/lib
 @ ./~/react-router/lib/match.js 13:37-79

ERROR in ./~/react-router/lib/match.js
Module not found: Error: Cannot resolve module 'history/lib/useBasename' in /Users/hubinjie/Documents/app/html5/react/react-weui/node_modules/react-router/lib
 @ ./~/react-router/lib/match.js 17:29-63
webpack: bundle is now VALID.

**Comment by progrape** [comment]
依赖的模块没有安装好？

**Comment by hubinjie** [comment]
npm WARN EPEERINVALID react-router@1.0.3 requires a peer of history@^1.17.0 but none was installed.

**Comment by hubinjie** [comment]
解决了：
npm install history@^1.17.0
npm install
