### ISSUE TITLE
webpack打包后bundle文件体积过大

### ISSUE THREAD

**Issue by andythink** [weui/react-weui#53]
@n7best 
你好@n7best，我按照文档中的例子，
```javascirpt
import React from 'react';
import ReactDOM from 'react-dom';
import WeUI from 'react-weui';
import 'weui';

const {Button} = WeUI;

class App extends React.Component {
    render() {
        return (
            <Button>hello wechat</Button>
        );
    }
}

ReactDOM.render(
    <App/>
), document.getElementById('container'));
```
这样用webpack打包后的bundle文件有1M多，手机打开需要很长时间，这样根本不能用在实际项目中用啊？？

**Comment by haibinyu** [comment]
生产环境一般都要使用production模式，然后minify再压缩，文件会小很多。
另外如果只使用到了某个控件，比如button，可以只导入button组件：
`import Button from 'weui/src/components/button`

**Comment by n7best** [comment]
你可以看看gh-pages的[bundle](https://github.com/weui/react-weui/blob/gh-pages/bundle.js)只有189k

webpack实际使用时像@haibinyu说的一样用production模式，不够满意的话还可以份为不同的chunk对应页面

**Comment by andythink** [comment]
@haibinyu 我已经开启了压缩，import Button from 'weui/src/components/button这样方式页试过，效果不理想，你说的production模式，可以详细的说一下？

**Comment by andythink** [comment]
@n7best gh-pages的bundle是怎么做的，我看到官网的http://weui.github.io/react-weui/#/button?_k=6pocfx  有两个js，verndor.js（101kb） bundle.js（42kb），请问是怎么处理的？

**Comment by haibinyu** [comment]
@andythink 在webpack.config.js的plugins中加入：
```js
new webpack.DefinePlugin({
            'process.env': {NODE_ENV:  JSON.stringify("production")}
})
```
试试

**Comment by haibinyu** [comment]
@andythink  基本是webpack配置的问题，建议看一下webpack的官方文档。

**Comment by andythink** [comment]
@haibinyu 好的，多谢
我试了只引入单个组件不行
import Button from 'react-weui/src/components/button这个编译不通过
import Button from 'react-weui/lib/components/button' 这个可以编译，但运行时报错

**Comment by andythink** [comment]
我的webpac配置
```javascript
devtool: false,
    plugins: [
        new webpack.optimize.UglifyJsPlugin({
            sourceMap: false,
            mangle: false
        }),
        new webpack.DefinePlugin({
            'process.env': {NODE_ENV:  JSON.stringify("production")}
        })
    ]
```
css文件是单独在页面引用的，官网的例子，打包后bundle.js (541K)，还是挺大的

**Comment by n7best** [comment]
@progrape 更新下例子的webpack config?

**Comment by progrape** [comment]
@andythink hi，你引入这个 `import Button from 'react-weui/src/components/button` 编译不通过，可能还是配置参数的问题（例如我们有`.babelrc` 文件），可以看看报错信息，对应来解决。理论上是可以单独引入组件的。

我们更新一下例子的 webpack.config.js 文件，尽量使得上手起来更方便。

**Comment by andythink** [comment]
@progrape 我的babelrc配置如下
```javascript
{
  "stage": 2,
  "optional": ["es7.classProperties"]
}
```

**Comment by progrape** [comment]
@andythink 如果全部打包成一个 `bundle` 文件，确实会比较大，更新起来也麻烦，需要一整个大文件更新。

更合理的做法应该是，将依赖的第三方库打包成一个独立的文件，因为它们更新频率相对较低，可以有效地缓存下来；自己开发的业务代码，单独打包成一个文件，有修改的时候，只需要更新这个文件，不用动依赖第三方的模块。以 react-weui 的 demo 代码为例，初步优化后，全部依赖的第三方库 gzip 传输大小为 `103 KB`，业务代码为`65.4 KB`（develop 分支）。

再者，我们代码里面引用 `weui`， 是通过 `import "weui"` 的形式的应用样式文件的，这部分也相对独立，也可以单独输出，替换成我们提供的 CDN 链接，减少加载时间，也可以充分利用缓存。

demo 打包的配置文件 https://github.com/weui/react-weui/blob/develop/webpack.config.js

**Comment by andythink** [comment]
@progrape 按照你的做法，基本已经可以满足在项目中使用。
@n7best @progrape @haibinyu  遇到问题能够及时的得到回应，即使目前有些问题，但还是有信心用下去

**Comment by andythink** [comment]
import Button from 'react-weui/src/components/button  这样单独引用还是报错
```javascript
node_modules/react-weui/src/components/button/index.js Line 7: Unexpected token
You may need an appropriate loader to handle this file type.
| 
| 
| import Button from './button';
| import ButtonArea from './button_area';
| 
 @ ./src/entry.js 28:36-79
```
项目的根目录已经配置了.babelrc
```json
{
  "stage": 2,
  "optional": ["es7.classProperties"]
}
```

**Comment by n7best** [comment]
直接用src引用组件的话 环境配置基本需要一样的 可以参考开发步骤

**Comment by progrape** [comment]
如果你是通过 npm 安装下来的，可以试试引入 lib 目录下的文件。发布到 npm 的模块包含了 lib 目录，里面的文件是编译好的。

**Comment by bengle** [comment]
有可能是sourcemap占据了大量空间，我也碰到了这个问题，去掉sourcemap体积减少了50%以上，再压缩一下就差不多可以了。现在的问题是sourcemap到底是不是必要的呢？牺牲性能来方便调试？

**Comment by progrape** [comment]
开发环境可以启用，生产环境就没必要了

**Comment by yuweilan** [comment]
求问大神们，http://weui.github.io/react-weui/#/button?_k=6pocfx  这个是怎么压缩这么小的
(bundle.js 64k,weui.min.css 9.3k,vendor.bundle.js 101k)
而我将例子里的example build之后大小是这样的(bundle.js 273k,weui.min.css 36k,vendor.bundle.js 180k)

**Comment by haibinyu** [comment]
gzip

**Comment by nicky9112** [comment]
问下 react-weui 有没有 CDN ? 地址是多少?

**Comment by jonahfang** [comment]
我也比较关注这个问题，能否像react/react-dom那样通过webpack的externals设置排除在最终打包文件之外：
```
  externals: {
    'react': 'React',
    'react-dom': 'ReactDOM'
  },
```
