### ISSUE TITLE
0.3 beta issues

### ISSUE THREAD

**Issue by n7best** [weui/react-weui#59]
Navbar:

- [ios] Not able switching tabs in real devices [fixed with #63] [cause weui/weui#298]

Searchbar:

-  [ios] cancel icon not responding when tap on real device [fixed with #63]

**Comment by progrape** [comment]
https://github.com/weui/weui/pull/298

**Comment by n7best** [comment]
@progrape  所以navbar只需要等weui css更新嘛

**Comment by progrape** [comment]
weui 的 v0.4.1 已发布，可以更新一下 react-weui 依赖的 weui 版本

**Comment by progrape** [comment]
#65
