### ISSUE TITLE
 import 'weui'; 作用是什么

### ISSUE THREAD

**Issue by tianyuanzhonglu** [weui/react-weui#61]
浏览器/webpack提示无法找到weui module

**Comment by progrape** [comment]
@tianyuanzhonglu weui 模块是指 https://github.com/weui/weui 这边的 CSS。react-weui 这里不包含 weui 的样式，需要引入 CSS 文件。可以通过以下方式引入：

1. 直接在 HTML 文件中通过 `link` 标签引入 `weui.css` 文件
2. 在 js 文件中通过 `import 'weui'` 的方式引入，使用 webpack 打包

第二种方式，也就是 react-weui 的 demo 和 你提到的方式，需要通过 `npm install weui --save` 的方式获取 weui （放在 `node_modules/weui` 目录），webpack 打包脚本中也需要指定 CSS 的处理规则，可以参考 https://github.com/weui/react-weui/blob/master/webpack.config.js#L28。

你出现的无法找到 weui module，应该是没有 `npm install weui` 获取到 weui 的原因。

**Comment by tianyuanzhonglu** [comment]
root cause：webpack脚本中没有指定CSS规则，和`npm install weui`无关。
建议css部分使用html link方式更好些，符合常识，避免绑定wepack这类打包工具。
