### ISSUE TITLE
Toast 组件更换 icon 后，icon 怎么变大？

### ISSUE THREAD

**Issue by zaxlct** [weui/react-weui#62]
![image](https://cloud.githubusercontent.com/assets/14342431/14308150/d8bd94c2-fc06-11e5-8c08-c87a9665fb17.png)
```jsx
<Toast show={this.state.success} icon="waiting_circle" >加载中...</Toast>
```
郁闷

**Comment by n7best** [comment]
这个版本被固定死了 除非延伸 那个icon的css, 下个版本应该会加入自定义
