### ISSUE TITLE
Toast 组件用方法调用似乎不符合 React 哲学

### ISSUE THREAD

**Issue by cncolder** [weui/react-weui#7]
之前 n7 的设计是用 `show` 属性控制显示, 个人更喜欢之前的设计.
用属性控制显示的好处是属性可以接受 `state` 或其他 `store` 传递来的数据.

**Comment by progrape** [comment]
欢迎参与探讨，使用属性控制确实可以通过`state`或者其他变量来控制。但是如果需求简单，就是某种情况下show出来，完了隐藏掉，也需要单独维护一个state，会不会变得麻烦呢？

**Comment by cncolder** [comment]
可以只稍微改一下现有的实现, 让`state.active` 读取 `props.show` 的值作为默认值, 这样如果不设置 `props.show` 的时候默认就是 `false`. 后续还是可以调用 `.show()` 和 `.close()` 来控制.

**Comment by n7best** [comment]
我想就是尽量不需要单独用到组件方法 能不要state就不要 要state的话能用属性控制就用属性控制。因为比如说在loading的话就是上级组件的一个state loading来决定就好了

**Comment by cncolder** [comment]
同意 @n7best , React 的理念是单向数据流, 组件会随着数据的变化局部刷新.
如果想要调用组件的方法, 首先要获得它的变量, 或者使用 `ref`.
带方法的组件会让它显得更像一个传统的 js 工具.

我之前提到的修改方案仔细想一下并不合适, 因为 `.show()` 方法修改 `state`, 会被随后的数据更新顶掉.

**Comment by progrape** [comment]
组件简单的话，组件内维护一个`state`，通过方法暴露，并没有什么大问题。不过可以像两位说的那样，统一使用属性往下传递的方式来进行，保持简单、统一~

**Comment by shihongzhi** [comment]
首先赞一下这个库。  赞同用 属性show的方式来控制 组件的显示。  看目前代码已经修改， 不过这份 [文档](https://github.com/progrape/react-weui/blob/master/docs/installation.md) 还未修改~

**Comment by progrape** [comment]
囧，toast的说明文档改了，上手文档的示例没改，我改一下，谢谢提醒~

**Comment by tlightsky** [comment]
nice，最近正好用得着Loading的Toast
