### ISSUE TITLE
peer依赖中react版本问题

### ISSUE THREAD

**Issue by DengKe1994** [weui/react-weui#82]
161 error peerinvalid The package react@15.0.2 does not satisfy its siblings' peerDependencies requirements!
161 error peerinvalid Peer react-addons-css-transition-group@0.14.8 wants react@^0.14.8
161 error peerinvalid Peer react-addons-test-utils@0.14.8 wants react@^0.14.8
161 error peerinvalid Peer react-dom@0.14.8 wants react@^0.14.8
161 error peerinvalid Peer enzyme@1.6.0 wants react@0.13.x || 0.14.x

 "react": "^0.14.2 || ^15.0.1" 这句有毒...

**Comment by uixdk** [comment]
怎么改了，求助啊，我也卡到这一步了啊

**Comment by n7best** [comment]
@DengKe1994 @uixdk npm啥版本

**Comment by uixdk** [comment]
@n7best          3.8.6

**Comment by uixdk** [comment]
@n7best 
升级node之后


> fsevents@1.0.12 install /Users/panduozhi/opensource/weui/react-weui/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

2016-05-19 22:43:12.365 xcodebuild[12413:785503] Build settings from command line:
2016-05-19 22:43:12.365 xcodebuild[12413:785503]     TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault
2016-05-19 22:43:12.366 xcodebuild[12413:785503]     XCODE_DEFAULT_TOOLCHAIN_OVERRIDE = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
  SOLINK_MODULE(target) Release/.node
ld: warning: URGENT: building for OSX, but linking against dylib (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/lib/libstdc++.dylib) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking against dylib (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/lib/libSystem.dylib) built for iOS. Note: This will be an error in the future.
  CXX(target) Release/obj.target/fse/fsevents.o
../fsevents.cc:11:10: fatal error: 'CoreServices/CoreServices.h' file not found
#include "CoreServices/CoreServices.h"
         ^
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/panduozhi/opensource/weui/react-weui/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/panduozhi/opensource/weui/react-weui/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64"
gyp ERR! cwd /Users/panduozhi/opensource/weui/react-weui/node_modules/fsevents
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/panduozhi/opensource/weui/react-weui/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node --module_name=fse --module_path=/Users/panduozhi/opensource/weui/react-weui/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/panduozhi/opensource/weui/react-weui/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Darwin 15.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/panduozhi/opensource/weui/react-weui/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/panduozhi/opensource/weui/react-weui/node_modules/fsevents
node-pre-gyp ERR! node -v v6.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.25
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/panduozhi/opensource/weui/react-weui/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node --module_name=fse --module_path=/Users/panduozhi/opensource/weui/react-weui/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64' (1)
npm WARN install:fsevents@1.0.12 fsevents@1.0.12 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:fsevents@1.0.12 Exit status 1
react-weui@0.4.0 /Users/panduozhi/opensource/weui/react-weui
└── UNMET PEER DEPENDENCY react@15.0.2 extraneous

npm WARN enzyme@1.6.0 requires a peer of react@0.13.x || 0.14.x but none was installed.
npm WARN react-addons-css-transition-group@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-addons-test-utils@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-dom@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm ERR! code 1

**Comment by n7best** [comment]
先npm install react 然后再instal react-weui看看

**Comment by DengKe1994** [comment]
@n7best 我的是2.12.1，我npm install react@^0.14.2可以了， peer依赖为什么要15.0.x？其他组件都依赖0.14.x。

**Comment by n7best** [comment]
@DengKe1994 引用的人用的可能是0.14或则0.15所以要分开来
