### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by uixdk** [weui/react-weui#85]
执行
npm install
npm start

报下面的错误：

ERROR in multi vendor
Module not found: Error: Cannot resolve module 'react' in /Users/xxx/opensource/weui/react-weui/example
 @ multi vendor

ERROR in ./~/react-dom/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactDOM' in /Users/xxx/opensource/weui/react-weui/node_modules/react-dom
 @ ./~/react-dom/index.js 3:17-46

ERROR in ./~/react-addons-css-transition-group/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactCSSTransitionGroup' in /Users/xxx/opensource/weui/react-weui/node_modules/react-addons-css-transition-group
 @ ./~/react-addons-css-transition-group/index.js 1:17-61

ERROR in ./example/app.js
Module not found: Error: Cannot resolve module 'react' in /Users/xxx/opensource/weui/react-weui/example
 @ ./example/app.js 17:13-29

ERROR in ./~/react-router/lib/Router.js
Module not found: Error: Cannot resolve module 'react' in /Users/xxx/opensource/weui/react-weui/node_modules/react-router/lib
 @ ./~/react-router/lib/Router.js 19:13-29

ERROR in ./~/react-router/lib/Link.js
Module not found: Error: Cannot resolve module 'react' in /Users/xxx/opensource/weui/react-weui/node_modules/react-router/lib
 @ ./~/react-router/lib/Link.js 15:13-29

ERROR in ./~/react-router/lib/IndexLink.js
Module not found: Error: Cannot resolve module 'react' in /Users/xxx/opensource/weui/react-weui/node_modules/react-router/lib
 @ ./~/react-router/lib/IndexLink.js 13:13-29

ERROR in ./~/react-router/lib/IndexRedirect.js
Module not found: Error: Cannot resolve module 'react' in /Users/xxx/opensource/weui/react-weui/node_modules/react-router/lib
 @ ./~/react-router/lib/IndexRedirect.js 19:13-29

ERROR in ./~/react-router/lib/IndexRoute.js
Module not found: Error: Cannot resolve module 'react' in /Users/xxx/opensource/weui/react-weui/node_modules/react-router/lib
 @ ./~/react-router/lib/IndexRoute.js 19:13-29

**Comment by youngBrain1893** [comment]
npm install react 试试，看这报错像是 React 没有安装上的样子

**Comment by uixdk** [comment]
npm WARN react-weui@0.4.0 requires a peer of react@^0.14.2 || ^15.0.1 but none was installed.
npm WARN react-addons-test-utils@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-addons-css-transition-group@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-dom@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN enzyme@1.6.0 requires a peer of react@0.13.x || 0.14.x but none was installed.

**Comment by n7best** [comment]
集中 #82 解决
