### ISSUE TITLE
文件上传 onChange

### ISSUE THREAD

**Issue by huliyou** [weui/react-weui#86]
文件上传 onChange 第一个参数返回的值是Object，应该是File
![image](https://cloud.githubusercontent.com/assets/3860373/15390205/4550ae96-1ded-11e6-8ba9-425ef57a145e.png)

![image](https://cloud.githubusercontent.com/assets/3860373/15390198/33ead578-1ded-11e6-9576-cbd559877279.png)

**Comment by n7best** [comment]
#80
