### ISSUE TITLE
import了react-weui后，就没法用热插拔了

### ISSUE THREAD

**Issue by terranc** [weui/react-weui#88]
是有这个问题吗？只要import了react-weui，不管有没有用到，其它自定义的组件更新都无法热插拔了。

**Comment by n7best** [comment]
暂时没遇到 能post下具体设置吗

**Comment by terranc** [comment]
就是一个小demo，本来可以热插拔的hello world，在定义的component里面import react-weui，就不行了。报什么moudeId啥的
