### ISSUE TITLE
如何与现有的路由方案集成？

### ISSUE THREAD

**Issue by haibinyu** [weui/react-weui#92]
现在weui的组件没有一个好的接口与react常用的路由方案（比如react-router）集成。
比如Cell中带props href的时候直接render成
`<a href="***"></a>`
但是大多数情况下，需要用react-router的Link来渲染，这个有没有什么好的解决方案？

**Comment by n7best** [comment]
这的确是个问题 我也有碰到 还在找解决方案

不过因为react-weui只是套weui的结构 我暂时解决方法就是给link单独加个weui的classname.

如果有更好的解决方法 可以分享分享

**Comment by haibinyu** [comment]
@n7best  暂时和你的方法一样.

**Comment by n7best** [comment]
1.0.0的Cell会加入一个component属性 用来定义Cell的属性 (react-router)的话 放Link进去就行了

**Comment by menthe** [comment]
如何替换呢？
