### ISSUE TITLE
按照要求安装启动以后报错，报错信息如下

### ISSUE THREAD

**Issue by yuweilan** [weui/react-weui#95]
ERROR in multi vendor
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example
 @ multi vendor

ERROR in ./~/react-addons-css-transition-group/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactCSSTransitionGroup' in E:\demo\weixin\react-weui\node_modules\react-addons-css-transition-group
 @ ./~/react-addons-css-transition-group/index.js 1:17-61

ERROR in ./~/react-dom/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactDOM' in E:\demo\weixin\react-weui\node_modules\react-dom
 @ ./~/react-dom/index.js 3:17-46

ERROR in ./example/app.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example
 @ ./example/app.js 17:13-29

ERROR in ./~/react-router/lib/Router.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\node_modules\react-router\lib
 @ ./~/react-router/lib/Router.js 19:13-29

ERROR in ./~/react-router/lib/Link.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\node_modules\react-router\lib
 @ ./~/react-router/lib/Link.js 15:13-29

ERROR in ./~/react-router/lib/IndexLink.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\node_modules\react-router\lib
 @ ./~/react-router/lib/IndexLink.js 13:13-29

ERROR in ./~/react-router/lib/IndexRedirect.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\node_modules\react-router\lib
 @ ./~/react-router/lib/IndexRedirect.js 19:13-29

ERROR in ./~/react-router/lib/Redirect.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\node_modules\react-router\lib
 @ ./~/react-router/lib/Redirect.js 15:13-29

ERROR in ./~/react-router/lib/IndexRoute.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\node_modules\react-router\lib
 @ ./~/react-router/lib/IndexRoute.js 19:13-29

ERROR in ./~/react-router/lib/Route.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\node_modules\react-router\lib
 @ ./~/react-router/lib/Route.js 15:13-29

ERROR in ./~/react-router/lib/Lifecycle.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\node_modules\react-router\lib
 @ ./~/react-router/lib/Lifecycle.js 7:13-29

ERROR in ./~/react-router/lib/RouteContext.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\node_modules\react-router\lib
 @ ./~/react-router/lib/RouteContext.js 7:13-29

ERROR in ./~/react-router/lib/RouteUtils.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\node_modules\react-router\lib
 @ ./~/react-router/lib/RouteUtils.js 14:13-29

ERROR in ./~/react-router/lib/RoutingContext.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\node_modules\react-router\lib
 @ ./~/react-router/lib/RoutingContext.js 17:13-29

ERROR in ./~/react-router/lib/PropTypes.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\node_modules\react-router\lib
 @ ./~/react-router/lib/PropTypes.js 6:13-29

ERROR in ./example/pages/home/index.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\home
 @ ./example/pages/home/index.js 21:13-29

ERROR in ./example/pages/cell/index.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\cell
 @ ./example/pages/cell/index.js 23:13-29

ERROR in ./example/pages/toast/index.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\toast
 @ ./example/pages/toast/index.js 21:13-29

ERROR in ./example/pages/button/index.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\button
 @ ./example/pages/button/index.js 21:13-29

ERROR in ./example/pages/progress/index.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\progress
 @ ./example/pages/progress/index.js 21:13-29

ERROR in ./example/pages/msg/index.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\msg
 @ ./example/pages/msg/index.js 21:13-29

ERROR in ./example/pages/dialog/index.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\dialog
 @ ./example/pages/dialog/index.js 21:13-29

ERROR in ./example/pages/article/index.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\article
 @ ./example/pages/article/index.js 21:13-29

ERROR in ./example/pages/actionsheet/index.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\actionsheet
 @ ./example/pages/actionsheet/index.js 21:13-29

ERROR in ./example/pages/icons/index.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\icons
 @ ./example/pages/icons/index.js 21:13-29

ERROR in ./example/pages/tab/index.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\tab
 @ ./example/pages/tab/index.js 21:13-29

ERROR in ./example/pages/tab/navbar.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\tab
 @ ./example/pages/tab/navbar.js 21:13-29

ERROR in ./example/pages/tab/navbar_auto.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\tab
 @ ./example/pages/tab/navbar_auto.js 21:13-29

ERROR in ./example/pages/tab/tabbar.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\tab
 @ ./example/pages/tab/tabbar.js 21:13-29

ERROR in ./example/pages/tab/tabbar_auto.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\tab
 @ ./example/pages/tab/tabbar_auto.js 21:13-29

ERROR in ./example/pages/panel/index.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\panel
 @ ./example/pages/panel/index.js 21:13-29

ERROR in ./example/pages/searchbar/index.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\pages\searchbar
 @ ./example/pages/searchbar/index.js 21:13-29

ERROR in ./example/component/page.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\example\component
 @ ./example/component/page.js 21:13-29

ERROR in ./src/components/icon/index.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\icon
 @ ./src/components/icon/index.js 13:13-29

ERROR in ./src/components/button/button.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\button
 @ ./src/components/button/button.js 27:13-29

ERROR in ./src/components/form/form_cell.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\form
 @ ./src/components/form/form_cell.js 27:13-29

ERROR in ./src/components/button/button_area.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\button
 @ ./src/components/button/button_area.js 21:13-29

ERROR in ./src/components/form/textarea.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\form
 @ ./src/components/form/textarea.js 27:13-29

ERROR in ./src/components/form/form.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\form
 @ ./src/components/form/form.js 27:13-29

ERROR in ./src/components/form/input.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\form
 @ ./src/components/form/input.js 27:13-29

ERROR in ./src/components/form/radio.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\form
 @ ./src/components/form/radio.js 27:13-29

ERROR in ./src/components/form/switch.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\form
 @ ./src/components/form/switch.js 27:13-29

ERROR in ./src/components/form/select.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\form
 @ ./src/components/form/select.js 27:13-29

ERROR in ./src/components/label/label.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\label
 @ ./src/components/label/label.js 27:13-29

ERROR in ./src/components/form/checkbox.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\form
 @ ./src/components/form/checkbox.js 27:13-29

ERROR in ./src/components/mask/mask.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\mask
 @ ./src/components/mask/mask.js 25:13-29

ERROR in ./src/components/cell/cells.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\cell
 @ ./src/components/cell/cells.js 27:13-29

ERROR in ./src/components/form/uploader.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\form
 @ ./src/components/form/uploader.js 27:13-29

ERROR in ./src/components/cell/cell.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\cell
 @ ./src/components/cell/cell.js 27:13-29

ERROR in ./src/components/cell/cells_title.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\cell
 @ ./src/components/cell/cells_title.js 27:13-29

ERROR in ./src/components/cell/cells_tips.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\cell
 @ ./src/components/cell/cells_tips.js 27:13-29

ERROR in ./src/components/cell/cell_header.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\cell
 @ ./src/components/cell/cell_header.js 27:13-29

ERROR in ./src/components/cell/cell_body.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\cell
 @ ./src/components/cell/cell_body.js 27:13-29

ERROR in ./src/components/cell/cell_footer.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\cell
 @ ./src/components/cell/cell_footer.js 27:13-29

ERROR in ./src/components/toast/toast.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\toast
 @ ./src/components/toast/toast.js 21:13-29

ERROR in ./src/components/actionsheet/actionsheet.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\actionsheet
 @ ./src/components/actionsheet/actionsheet.js 27:13-29

ERROR in ./src/components/msg/msg.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\msg
 @ ./src/components/msg/msg.js 25:13-29

ERROR in ./src/components/dialog/confirm.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\dialog
 @ ./src/components/dialog/confirm.js 25:13-29

ERROR in ./src/components/article/article.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\article
 @ ./src/components/article/article.js 27:13-29

ERROR in ./src/components/progress/progress.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\progress
 @ ./src/components/progress/progress.js 23:13-29

ERROR in ./src/components/dialog/alert.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\dialog
 @ ./src/components/dialog/alert.js 25:13-29

ERROR in ./src/components/icon/icon.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\icon
 @ ./src/components/icon/icon.js 29:13-29

ERROR in ./src/components/grid/grid.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\grid
 @ ./src/components/grid/grid.js 25:13-29

ERROR in ./src/components/grid/grids.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\grid
 @ ./src/components/grid/grids.js 25:13-29

ERROR in ./src/components/grid/grid_icon.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\grid
 @ ./src/components/grid/grid_icon.js 25:13-29

ERROR in ./src/components/grid/grid_label.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\grid
 @ ./src/components/grid/grid_label.js 25:13-29

ERROR in ./src/components/mediabox/mediabox.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\mediabox
 @ ./src/components/mediabox/mediabox.js 25:13-29

ERROR in ./src/components/mediabox/mediabox_header.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\mediabox
 @ ./src/components/mediabox/mediabox_header.js 25:13-29

ERROR in ./src/components/mediabox/mediabox_title.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\mediabox
 @ ./src/components/mediabox/mediabox_title.js 25:13-29

ERROR in ./src/components/mediabox/mediabox_body.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\mediabox
 @ ./src/components/mediabox/mediabox_body.js 25:13-29

ERROR in ./src/components/mediabox/mediabox_desc.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\mediabox
 @ ./src/components/mediabox/mediabox_desc.js 25:13-29

ERROR in ./src/components/mediabox/mediabox_info.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\mediabox
 @ ./src/components/mediabox/mediabox_info.js 25:13-29

ERROR in ./src/components/mediabox/mediabox_info_meta.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\mediabox
 @ ./src/components/mediabox/mediabox_info_meta.js 25:13-29

ERROR in ./src/components/panel/panel.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\panel
 @ ./src/components/panel/panel.js 27:13-29

ERROR in ./src/components/panel/panel_header.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\panel
 @ ./src/components/panel/panel_header.js 25:13-29

ERROR in ./src/components/panel/panel_body.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\panel
 @ ./src/components/panel/panel_body.js 25:13-29

ERROR in ./src/components/panel/panel_footer.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\panel
 @ ./src/components/panel/panel_footer.js 25:13-29

ERROR in ./src/components/tab/tab.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\tab
 @ ./src/components/tab/tab.js 25:13-29

ERROR in ./src/components/tab/tab_body.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\tab
 @ ./src/components/tab/tab_body.js 25:13-29

ERROR in ./src/components/tab/navbar.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\tab
 @ ./src/components/tab/navbar.js 25:13-29

ERROR in ./src/components/tab/navbar_item.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\tab
 @ ./src/components/tab/navbar_item.js 25:13-29

ERROR in ./src/components/tab/tabbar.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\tab
 @ ./src/components/tab/tabbar.js 25:13-29

ERROR in ./src/components/tab/tabbar_item.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\tab
 @ ./src/components/tab/tabbar_item.js 25:13-29

ERROR in ./src/components/tab/tabbar_icon.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\tab
 @ ./src/components/tab/tabbar_icon.js 25:13-29

ERROR in ./src/components/tab/tabbar_label.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\tab
 @ ./src/components/tab/tabbar_label.js 25:13-29

ERROR in ./src/components/tab/tab_body_item.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\tab
 @ ./src/components/tab/tab_body_item.js 25:13-29

ERROR in ./src/components/searchbar/searchbar.js
Module not found: Error: Cannot resolve module 'react' in E:\demo\weixin\react-weui\src\components\searchbar
 @ ./src/components/searchbar/searchbar.js 23:13-29

**Comment by progrape** [comment]
> Module not found: Error: Cannot resolve module 'react' 

请检查一下 react 是否有正确安装

**Comment by yuweilan** [comment]
按照package中的配置直接install的，安装完了之后报了个这个
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12

刚才又install了一下，报的
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN react-weui@0.4.0 requires a peer of react@^0.14.2 || ^15.0.1 but none was installed.
npm WARN enzyme@1.6.0 requires a peer of react@0.13.x || 0.14.x but none was installed.
npm WARN react-addons-css-transition-group@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-addons-test-utils@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-dom@0.14.8 requires a peer of react@^0.14.8 but none was installed.

package中的这个没有用么？
"peerDependencies": {
        "react": "^0.14.2 || ^15.0.1"
    }

谢谢帮助

**Comment by progrape** [comment]
你可能用的是 npm3 ，可以参考一下这里

http://stackoverflow.com/questions/35207380/how-to-install-npm-peer-dependencies-automatically

**Comment by yuweilan** [comment]
是的，我用的npm3，必须用低版本的npm才能正常运行么？

**Comment by progrape** [comment]
也不是必须低版本，可以手动安装一下 `npm install react` 试试

**Comment by yuweilan** [comment]
手动npm install react@^0.14.2了一下，能跑了，求问大神版本能更新一下么？估计后来的也会遇到这个坑

**Comment by n7best** [comment]
@progrape https://codingwithspike.wordpress.com/2016/01/21/dealing-with-the-deprecation-of-peerdependencies-in-npm-3/ 可以像这个人这样都添加 这样解决npm2 和npm3

或则说readme 直接写 npm install react react-weui 这样

**Comment by peterz3g** [comment]
cnpm install react@^0.14.2 就好了.  哎!也踩了坑,坑,坑啊.
