### ISSUE TITLE
vendor.bundle.js这个是压缩的js资源文件么？

### ISSUE THREAD

**Issue by yuweilan** [weui/react-weui#97]
vendor.bundle.js是
vendor: ['react', 'classnames', 'react-router', 'react-dom', 'react-addons-css-transition-group']
这些压缩打包的么？

**Comment by yuweilan** [comment]
我把咱的项目下载以后，打包example里的文件生成dist文件夹，里面的bundle.js有273k,vendor.bundle.js有180k，而咱们的demo线上bundle.js只有64k,vendor.bundle.js有101k，这是怎么回事儿？

麻烦了，谢谢

**Comment by yuweilan** [comment]
@progrape 求助大神

**Comment by haibinyu** [comment]
gzip

**Comment by progrape** [comment]
@yuweilan 这些是 webpack 的配置，具体使用方式可以参考 webpack 的文档 http://webpack.github.io/

**Comment by yuweilan** [comment]
@haibinyu 不好意思，不是很懂gzip不是webpack中的命令吧？
react-weui 的 demo中https://github.com/weui/react-weui/blob/develop/webpack.config.js  不是已经算是压缩了么？
new webpack.optimize.UglifyJsPlugin({
            sourceMap: false,
            mangle: false
}),

**Comment by haibinyu** [comment]
你看到的是数据传输大小吧，官网用了nginx之类的web服务器吧，开了gzip，传输大小就比实际文件大小小很多了。

**Comment by yuweilan** [comment]
好的，明白了，十分感谢
