### ISSUE TITLE
clone 后项目跑不起来

### ISSUE THREAD

**Issue by dancinglone** [weui/react-weui#98]
按此说明运行项目：
开发
git clone https://github.com/weui/react-weui
cd react-weui
npm install
npm start

报错如下：

> react-weui@0.4.0 start /Users/PPfix/Desktop/weui/react-weui
> webpack-dev-server --hot --inline --progress --colors --port 8080

 70% 2/2 build modulesevents.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:77:26)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! react-weui@0.4.0 start: `webpack-dev-server --hot --inline --progress --colors --port 8080`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-weui@0.4.0 start script 'webpack-dev-server --hot --inline --progress --colors --port 8080'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-weui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --hot --inline --progress --colors --port 8080
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-weui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/PPfix/Desktop/weui/react-weui/npm-debug.log

望赐教

**Comment by progrape** [comment]
报错信息是说没有绑到指定的 host。你可以通过以下两种方式来解决：

1. 在 `package.json` 的 `scripts.start` 属性显示指定绑的 hosts，`webpack-dev-server --hot --inline --progress --colors --port 8080 --host 0.0.0.0`

2. 修改你机器的 hosts 文件，将 localhost 指向 127.0.0.1

```
sudo vim /etc/hosts
```

加上 `127.0.0.1 localhost` 这一段

**Comment by dancinglone** [comment]
问题解决了，感谢！ 是我个人水平问题。。。    这个 issue 对大家没什么参考价值。。。可以关掉了

**Comment by dancinglone** [comment]
有更详细一点的文档吗，刚接受 react，觉得不太能驾驭啊。    用 npm build  命令，好像没有成功 build，因为看不到输出文件目录和 build的log 信息。
DCLs-Mac-mini:react-weui PPfix$ npm build
DCLs-Mac-mini:react-weui PPfix$ 
命令这样跑了没 报错，但又什么都没见到。

**Comment by dancinglone** [comment]
有谁遇到同样的问题吗？应该怎样构建出可以直接在生产环境跑的，最基本的版本？

**Comment by yuweilan** [comment]
npm  run build
